version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local
    ports:
      - "5432:5432"
    networks:
      - bgg-lets-play

  db-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      - bgg-lets-play
networks:
  bgg-lets-play:
