org: franciscocallemoreno
console: true
service: serverless-bgg-lets-play

plugins:
  - serverless-jetpack
  - serverless-plugin-log-retention
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  logRetentionInDays: 3
  timeout: 10

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    environment:
      CACHE_TTL_IN_SECONDS: 3600
      CACHE_TYPE: file
      NO_COLOR: 1
    logRetentionInDays: 3
