-- AlterTable
ALTER TABLE "game_rating" ALTER COLUMN "average" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bayesaverage" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "stddev" SET DATA TYPE DOUBLE PRECISION;
